font_family JetBrainsMono Nerd Font
font_size 16
foreground #cdd6f4
background #1e1e2e
window_padding_width 8
hide_window_decorations yes
background_opacity 0.92
cursor_shape block
scrollback_lines 10000
include ~/.config/kitty/matugen.conf
