[config.wallpaper]
set = true
command = "awww"
arguments = ["img", "--resize", "fit"]

[templates.theme]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/theme/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/matugen.conf"
