background {
    path = screenshot
    blur_passes = 2
    blur_size = 4
}

input-field {
    size = 320, 55
    outline_thickness = 2
    outer_color = rgba(137,180,250,0.8)
    inner_color = rgba(30,30,46,0.75)
    font_color = rgba(205,214,244,1)
    position = 0, -70
    halign = center
    valign = center
}

label {
    text = $TIME
    font_size = 48
    color = rgba(205,214,244,0.9)
    position = 0, 80
    halign = center
    valign = center
}
